"""
Gradio demo for Parkinson's voice analysis.

This app runs on Hugging Face Spaces and provides a browser-based interface
for the trained model. Users can either upload a .wav file or record audio
directly in the browser, and the app returns a probability score along with
the extracted acoustic features.

This is a thin UI layer — all the ML logic (feature extraction, model
inference) is identical to the local CLI pipeline (`python -m src.predict`).
The same model artifacts are used in both places.

Disclaimer: This is an educational demo only. Not a medical device. Not a
diagnostic tool. See the full README for limitations.
"""

from __future__ import annotations

import json
from pathlib import Path

import gradio as gr
import joblib
import numpy as np
import pandas as pd

from features import extract_features


# ---------------------------------------------------------------------------
# Load model artifacts once at startup
# ---------------------------------------------------------------------------
# These files are committed alongside the app on Hugging Face Spaces so that
# inference works without retraining. They were generated by running
# `python -m src.train` in the main repo.
HERE = Path(__file__).resolve().parent

MODEL = joblib.load(HERE / "best_model.joblib")
SCALER = joblib.load(HERE / "scaler.joblib")
with open(HERE / "feature_names.json") as f:
    SCHEMA = json.load(f)

FEATURE_NAMES = SCHEMA["features"]
MODEL_NAME = SCHEMA["model"]


# ---------------------------------------------------------------------------
# Inference function
# ---------------------------------------------------------------------------
def analyze_voice(audio_path: str | None) -> tuple[dict, pd.DataFrame, str]:
    """
    Run the full inference pipeline on a single audio file.

    Args:
        audio_path: Local filesystem path provided by Gradio. When the user
                    records or uploads audio, Gradio writes it to a temp file
                    and passes the path here.

    Returns:
        Tuple of:
            - Label component data: dict mapping class names to probabilities
            - Feature table as a pandas DataFrame
            - Markdown summary string with key insights
    """
    if audio_path is None:
        return (
            {"No audio provided": 1.0},
            pd.DataFrame(),
            "**Please upload or record an audio file to analyze.**",
        )

    try:
        # Extract acoustic features using Praat. This is the exact same code
        # path as the CLI predict.py — single source of truth.
        features = extract_features(audio_path)
        feature_vector = features.to_feature_vector().reshape(1, -1)

        # Sanity check: feature order must match training time.
        actual_names = features.feature_names()
        if actual_names != FEATURE_NAMES:
            raise RuntimeError(
                f"Feature schema mismatch.\n"
                f"Expected: {FEATURE_NAMES}\n"
                f"Got:      {actual_names}"
            )

        # Apply the scaler that was fit on the training data.
        scaled = SCALER.transform(feature_vector)

        # Predict probability of the positive class.
        proba_pd = float(MODEL.predict_proba(scaled)[0, 1])
        proba_healthy = 1.0 - proba_pd

        # Build a nice feature table for display.
        feature_table = pd.DataFrame({
            "Feature": FEATURE_NAMES,
            "Value": [f"{v:.4f}" for v in feature_vector.flatten()],
        })

        # Build a human-readable summary.
        confidence = abs(proba_pd - 0.5) * 2.0
        predicted_class = "Parkinson's pattern detected" if proba_pd >= 0.5 else "Healthy pattern"

        summary = f"""
### Analysis Result

- **Prediction:** {predicted_class}
- **Probability (PD):** {proba_pd:.1%}
- **Model confidence:** {confidence:.1%}
- **Audio duration:** {features.duration_s:.2f}s @ {features.sample_rate} Hz
- **Model:** {MODEL_NAME}

### Key acoustic markers

- **Mean F0** (fundamental frequency): {features.mdvp_fo_hz:.1f} Hz
- **Jitter (local)**: {features.mdvp_jitter_pct:.3f}% — cycle-to-cycle pitch variation
- **Shimmer (local)**: {features.mdvp_shimmer:.4f} — cycle-to-cycle amplitude variation
- **HNR**: {features.hnr:.2f} dB — harmonics-to-noise ratio (lower = breathier voice)

> ⚠️ **Educational demo only.** This is not a medical diagnosis. See the
> [GitHub repo](https://github.com/vpatel2398/Parkinson-Disease-Detection-with-Audio)
> for the full methodology, limitations, and honest disclosures about
> dataset size and generalization.
        """.strip()

        return (
            {"Parkinson's": proba_pd, "Healthy": proba_healthy},
            feature_table,
            summary,
        )

    except Exception as e:
        # Gradio doesn't show exceptions nicely by default, so we return a
        # readable error message instead.
        error_msg = f"""
### Error analyzing audio

```
{type(e).__name__}: {e}
```

**Common causes:**
- Audio is too short (need 1+ seconds of sustained vowel)
- Audio doesn't contain voiced speech (silence, music, noise)
- Recording is too quiet — try speaking louder
- Wrong file format (use .wav if uploading)
        """.strip()
        return ({"Error": 1.0}, pd.DataFrame(), error_msg)


# ---------------------------------------------------------------------------
# UI definition
# ---------------------------------------------------------------------------
DESCRIPTION = """
# 🎙️ Parkinson's Voice Analysis Demo

Upload or record a **sustained `/a/` vowel** (5+ seconds works best) and the system
will extract 16 acoustic features using [Praat](https://www.fon.hum.uva.nl/praat/)
and run a Random Forest classifier trained on the UCI Parkinson's voice dataset.

**How to record a good sample:**
1. Click the microphone icon below
2. Take a deep breath
3. Say "aaaaaaaah" at a comfortable pitch for 5+ seconds
4. Stop the recording and click **Analyze**

---
"""

DISCLAIMER = """
### ⚠️ Important disclaimers

- **Not a medical device.** This model has not been clinically validated.
- **Cannot diagnose** Parkinson's disease or any condition.
- Trained on **31 subjects only** — results may not generalize to your demographic, language, or recording setup.
- For real concerns about voice or motor symptoms, see a neurologist.

This is a portfolio project demonstrating end-to-end ML engineering: scientifically
valid feature extraction (Praat), subject-grouped cross-validation, and honest
reporting of limitations. [Full methodology on GitHub](https://github.com/vpatel2398/Parkinson-Disease-Detection-with-Audio).
"""

with gr.Blocks(title="Parkinson's Voice Analysis", theme=gr.themes.Soft()) as demo:
    gr.Markdown(DESCRIPTION)

    with gr.Row():
        with gr.Column(scale=1):
            audio_input = gr.Audio(
                sources=["microphone", "upload"],
                type="filepath",
                label="Record or upload sustained /a/ vowel",
                format="wav",
            )
            analyze_btn = gr.Button("Analyze", variant="primary", size="lg")

        with gr.Column(scale=1):
            prob_output = gr.Label(
                label="Classification probability",
                num_top_classes=2,
            )

    summary_output = gr.Markdown(label="Detailed analysis")

    with gr.Accordion("Show all 16 acoustic features", open=False):
        feature_output = gr.Dataframe(
            label="Extracted features",
            headers=["Feature", "Value"],
            wrap=True,
        )

    gr.Markdown(DISCLAIMER)

    analyze_btn.click(
        fn=analyze_voice,
        inputs=audio_input,
        outputs=[prob_output, feature_output, summary_output],
    )


if __name__ == "__main__":
    demo.launch()
